FROM --platform=$BUILDPLATFORM docker.arvancloud.ir/golang:1.25-alpine AS build
WORKDIR /src

ENV GOPROXY=https://mirror-go.runflare.com
COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG TARGETOS
ARG TARGETARCH
ENV CGO_ENABLED=0

RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build \
    -ldflags="-s -w" \
    -trimpath \
    -o /out/sni-spoofing \
    .

FROM docker.arvancloud.ir/alpine:3.21
RUN apk add --no-cache ca-certificates iptables

COPY --from=build /out/sni-spoofing /usr/local/bin/sni-spoofing

ENTRYPOINT ["/usr/local/bin/sni-spoofing"]